name: Build and Deploy Sphinx Site to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python packages
        run: pip install -r ./.devcontainer/requirements.txt

      - name: Make static files
        run: sphinx-build -M dirhtml ./source ./build

      - name: Package and upload artifact of static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/dirhtml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy uploaded artifact to GitHub Pages
        uses: actions/deploy-pages@v4
